# Generated by Django 4.2.5 on 2023-10-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('qty', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('breakages', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('remarks', models.TextField()),
                ('room', models.CharField(choices=[('PR', 'Prep Room'), ('MS', 'Main Stockroom'), ('2F', '2nd Floor Chem. Lab')], default='PR', max_length=2)),
            ],
        ),
    ]
